on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
name: Mirror GitHub to Gitee
jobs:
  run:
    name: Sync-GitHub-to-Gitee
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/ventoy
        dst: gitee/LongPanda
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: "vdiskchain"
        force_update: true
